# Spring configuration
spring:
  profiles:
    active: qa
    include:
    - mysql
    - redis
  h2.console.enabled: false

# Cache


#flyway:
#  baseline-on-migrate: true
#  baseline-version: 1.0.0
#  baseline-description: initial db setup


# Logging
logging:
  level:
    root: ERROR
    org.springframework: INFO
    bright.zheng: INFO
  pattern:
    console: "==> [%p] %c{1}(%L) - %m%n"


# Actuator Configuration
endpoints:
  enabled: true
  info:
    enabled: false
  health:
    enabled: true
  metrics:
    enabled: false
